name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' # Ensure this matches your go.mod or project requirements

    - name: Display Go version
      run: go version

    # Dependencies are typically fetched during build or test,
    # but explicit download can be useful for caching later.
    - name: Download dependencies
      run: go mod download

    - name: Check formatting
      run: test -z $(gofmt -l .) || (echo "Code is not formatted. Run 'gofmt -w .' to format." && exit 1)

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run ./...

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run: $(go env GOPATH)/bin/govulncheck ./...

    - name: Run tests
      run: go test -race ./...

    - name: Build
      run: go build -v ./...
